### ISSUE TITLE
Update Webpack-Typescript-Template

### ISSUE THREAD

**Issue by mikey74L** [aurelia-ui-toolkits/syncfusion-templates-repository#7]
Could you update your webpack typescript template for the latest skeletons from aurelia team. In the current version easy webpack isn't used anymore and hot module reload is available.

**Comment by karthickthangasamy** [comment]
@mikey74L The updated skeleton is in development phase, we configured the [released](https://github.com/aurelia/skeleton-navigation/archive/1.1.2.zip) skeletons to avoid configuration issues as per Aurelia guidelines. We do the required changes, once the skeleton released with stable version.

Thanks for sharing the information.

**Comment by karthickthangasamy** [comment]
@mikey74L We documented steps to integrate `aurelia-syncfusion-bridge` into latest skeleton.

https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/wiki/Integration-with-skeleton-esnext-latest 

We hope, this helps to integrate the bridge with development mode skeletons.
